version: "3.8"
services:
  psql:
    container_name: db
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  django:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    depends_on:
      - psql

  react:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/frontend/src
volumes:
  postgres_data: